<script>
    async function f() {

let promise = new Promise((resolve, reject) => {
  setTimeout(() => reject(new Error("error")), 1000)
});
try{
        let result = await promise; // wait till the promise resolves (*)

}catch(err){
    console.log("error",err)
}

}

f();
</script>